version: '3.8'
services:
  syncly-crawler:
    image: ${IMAGE_URI}
    container_name: syncly-crawler-${ENVIRONMENT}
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3