name: ⚙️ Deploy Dispatcher

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: '배포 환경 선택'
        required: true
        type: environment

jobs:
  call-dev-workflow:
    if: inputs.target_environment == 'dev'
    uses: ./.github/workflows/deploy-dev.yml
    
  call-prod-workflow:
    if: inputs.target_environment == 'prod' 
    uses: ./.github/workflows/deploy-prod.yml